### ISSUE TITLE
Add preview for long javadoc texts

### ISSUE THREAD

**Issue by JohnnyJayJay** [PiggyPiglet/DocDex#20]
Currently, the bot simply posts a link to the web version of the javadoc if the requested description etc is too long. In my opinion, some sort of preview that is truncated to fit the Discord embed limits would be a good addition. The text could simply be cut off and `...` or something could be appended. This could result in ugly styling issues (e.g. if this happens in the middle of a code block), so a more sophisticated strategy might be worth discussing.

**Comment by PiggyPiglet** [comment]
> This could result in ugly styling issues (e.g. if this happens in the middle of a code block), so a more sophisticated strategy might be worth discussing.
This is the sole reason it doesn't have a truncated description already. Currently it doesn't keep html, it just gets the text. Once I add support for that through #19 though, something like this should be possible, as I can specifically cut off before an example starts.
