### ISSUE TITLE
Improve display of embeds

### ISSUE THREAD

**Issue by Andre601** [PiggyPiglet/DocDex#21]
I believe the embeds could deserve some minor restructuring...

Current:
![image](https://user-images.githubusercontent.com/11576465/104258729-6e6b3980-5480-11eb-8e5a-7046e349d008.png)

Suggestion (Made with Embed visualizer):
![image](https://user-images.githubusercontent.com/11576465/104259130-154fd580-5481-11eb-9aad-696cafd434c7.png)

**Comment by PiggyPiglet** [comment]
The implements Material looks like a bug. Also how do you recommend depicting abstract classes? Perhaps under package, we could have "declaration", which looks like:
```java
package: package.blah
declaration: public abstract class BlahBlah
extends: etc```

**Comment by JohnnyJayJay** [comment]
Just noting that I like the way it's currently done more since the type declaration is what you also get from web javadoc.

**Comment by Andre601** [comment]
> The implements Material looks like a bug. Also how do you recommend depicting abstract classes? Perhaps under package, we could have "declaration", which looks like:
> 
> ```yaml
> package: package.blah
> declaration: public abstract class BlahBlah
> extends: etc
> ```
> 
> I don't want to differentiate abstract classes & regular classes api wise, because abstract is a modifier, not a type. And simply scanning for the word "abstract" in the modifiers is not a good solution, as it's not forward compatible.

Not sure, but maybe display it in the title alongside the class type?
Like `abstract class Blah`? I'm not even sure if it was worth it to disokay the access level here as most if not all Javadocs only depict public classes from what I know.
But perhaps having a "access" section would be an idea? Like `access type: public`

**Comment by PiggyPiglet** [comment]
TBH splitting it up into declaration:, package:, etc seems like more bloat, which you just said isn’t necessarily good. I, like Johnny, prefer the way it’s currently done, which is the same way as it’s shown in the javadoc itself, which was fully intentional. Not closing this issue as there’s still a bug that needs to be resolved, and I also may change my opinion in the near future.
