### ISSUE TITLE
[Bot] Exact match not returned unless $ used in command

### ISSUE THREAD

**Issue by Laarryy** [PiggyPiglet/DocDex#24]
Had this conversation with the DocDex bot recently: 

![image](https://i.imgur.com/LfPfiQv.png)

It would be ideal if, given a limit of `n`, when an exact match is found to build an embed around that instead of returning the same query in a list of suggestions - giving the bot a limit, I had thought, would cause it to create several paginated embeds with the first result first, but even if this is not the case when an exact match *is* found but a limit other than 'first' is given, the error should probably not say that no match was found 😄

**Comment by PiggyPiglet** [comment]
The bug is a legitimate bug, I'll look into that, but the suggestion is the same as #18.
