### ISSUE TITLE
SnakeYaml Doc bug 

### ISSUE THREAD

**Issue by Jerry442** [PiggyPiglet/DocDex#3]
**d;snakeyaml Yaml#loadAs**
This command stated above fails to send the doc while it’s counterpart
**d;snakeyaml Yaml#load**
works fine this is likely due to the sneaky /./ in this:
[https://docdex.helpch.at/index?javadoc=snakeyaml&query=yaml~loadas](https://docdex.helpch.at/index?javadoc=snakeyaml&query=yaml~loadas)

**Comment by PiggyPiglet** [comment]
Not to do with the `.`, as it's present in both https://docdex.helpch.at/index?javadoc=snakeyaml&query=yaml~loadas & https://docdex.helpch.at/index?javadoc=snakeyaml&query=yaml~load. I assume it's todo with the space, perhaps discord doesn't convert it to %20.
