### ISSUE TITLE
Queries and Discord message formatting

### ISSUE THREAD

**Issue by iGabyTM** [PiggyPiglet/DocDex#43]
When using something like `d;spigot NamespacedKey#minecraft` it turns into an invalid query because on HelpChat, `#minecraft` it is a channel and DocDex takes the message literally. If possible, ignore such formatting (doesn't JDA have a method to get the _raw_ message, with `#minecraft` instead of `<#382856648064237568>`?).

**Comment by BomBardyGamer** [comment]
Are we using `getContentDisplay` or `getContentRaw` here? Because we should probably be using the latter, which does no processing to the message and always treats it as-is.
