### ISSUE TITLE
Some mismatch method queries return multiple copies of the same method

### ISSUE THREAD

**Issue by Fefo6644** [PiggyPiglet/DocDex#7]
### Description
Some (not all) mismatched method queries suggest certain methods multiple times when there is only one of them

### Examples
Spigot's [`ServicesManager`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/plugin/ServicesManager.html) only contains *one* `load` method yet it shows multiple:
![image](https://user-images.githubusercontent.com/35617540/103192603-02050d80-48b8-11eb-8576-7155f93d3bd2.png)

The JDK's [`Map`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.html) class contains in reality a single `get` method:
![image](https://user-images.githubusercontent.com/35617540/103192673-409ac800-48b8-11eb-980e-3e67d6511ab4.png)

**Comment by PiggyPiglet** [comment]
That's super weird. Iirc I'm returning a set in the query, duplicates shouldn't be possible. Not to mention, the actual data structure storing the objects is a set. Really not sure what's going on here, perhaps my hashcode/equals impl might be outdated

**Comment by PiggyPiglet** [comment]
Thought this could be solved via #9, but it looks like the issue actually stems from the fact that the identifier in the documented object, isn't actually necessarily what the object is actually called. For example, you can search for servicesmanager#load & simpleservicesmanager, but they both return the exact same object. I'm going to create a new type which is returned by the endpoint which contains the actual name the object is referenced by in memory, along with the object itself.
